
package Server;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.net.Socket;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import javax.swing.JOptionPane;


public class frmMailClient extends javax.swing.JFrame {

    /**
     * Creates new form frmMailClient
     */
    public frmMailClient() {
        initComponents();
    }
    private static final String SERVER_HOST = "localhost";
    private static final int SERVER_PORT = 1234;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnDangxuat = new javax.swing.JButton();
        btnThugui = new javax.swing.JButton();
        btnSoanthu = new javax.swing.JButton();
        btnHopthuden = new javax.swing.JButton();
        btnThurac = new javax.swing.JButton();
        btnThungrac = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtNguoigui = new javax.swing.JTextField();
        txtTieude = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNoidung = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnPhanhoi = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtnguoidanhan = new javax.swing.JTextField();
        btnGui = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnDangxuat.setText("Đăng xuất");
        btnDangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangxuatActionPerformed(evt);
            }
        });

        btnThugui.setText("Thư Đã Gửi");
        btnThugui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThuguiActionPerformed(evt);
            }
        });

        btnSoanthu.setText("Soạn Thư");
        btnSoanthu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSoanthuActionPerformed(evt);
            }
        });

        btnHopthuden.setText("Hộp Thư Đến");
        btnHopthuden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHopthudenActionPerformed(evt);
            }
        });

        btnThurac.setText("Thư Rác");
        btnThurac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThuracActionPerformed(evt);
            }
        });

        btnThungrac.setText("Thùng rác");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSoanthu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnThurac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnThugui, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHopthuden, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(btnThungrac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btnDangxuat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSoanthu)
                .addGap(8, 8, 8)
                .addComponent(btnHopthuden)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnThugui)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnThurac)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnThungrac)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(btnDangxuat)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Hộp Thư Đến");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Thời gian", "Người Gửi", "Tiêu Đề"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        txtNoidung.setColumns(20);
        txtNoidung.setRows(5);
        jScrollPane2.setViewportView(txtNoidung);

        jLabel2.setText("Người Gửi");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText("Tiêu Đề");

        jLabel4.setText("Nội Dung");

        btnPhanhoi.setText("Phản Hồi");
        btnPhanhoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhanhoiActionPerformed(evt);
            }
        });

        jLabel5.setText("Những người đã nhận email");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(txtnguoidanhan, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtnguoidanhan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        btnGui.setText("Gửi");
        btnGui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(499, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(382, 382, 382))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel4))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(txtNguoigui, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(txtTieude, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(67, 67, 67))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnPhanhoi)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(btnGui)
                                            .addGap(15, 15, 15)))
                                    .addGap(32, 32, 32))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(23, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNguoigui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTieude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addGap(113, 113, 113)
                                .addComponent(btnPhanhoi)
                                .addGap(16, 16, 16)))
                        .addGap(18, 18, 18)
                        .addComponent(btnGui))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangxuatActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnDangxuatActionPerformed

    private void btnSoanthuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSoanthuActionPerformed
        frmSend f = new frmSend();
        f.setVisible(true);
    }//GEN-LAST:event_btnSoanthuActionPerformed

    private void loaddata(List<EmailData> emailDataList) {
        try {
            DefaultTableModel tableModel = new DefaultTableModel();
            String[] columnNames = {"Thời gian", "Người gửi", "Tiêu đề", "Nội dung"};
            for (String columnName : columnNames) {
                tableModel.addColumn(columnName);
            }
            jTable1.setModel(tableModel);

            // Xóa dữ liệu cũ trong JTable (nếu có)
            while (tableModel.getRowCount() > 0) {
                tableModel.removeRow(0);
            }

            // Thêm dữ liệu mới từ danh sách emailDataList vào JTable
            for (EmailData emailData : emailDataList) {
                Object[] rowData = {
                    emailData.getTimestamp(),
                    emailData.getUsername(),
                    emailData.getSubject(),
                    emailData.getBody()
                };
                tableModel.addRow(rowData);
            }

            // Làm gì đó với txtNguoigui, txtTieude và txtNoidung (nếu cần)
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    List<EmailData> emailDataList;
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setGD(false);
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("Timestamp");
        tableModel.addColumn("Username");
        tableModel.addColumn("Subject");
        tableModel.addColumn("Body");
        try {
            Socket clientSocket = new Socket(SERVER_HOST, SERVER_PORT);
            DataOutputStream outputStream = new DataOutputStream(clientSocket.getOutputStream());

            outputStream.writeUTF("hopthuden");
            outputStream.flush();

            // Tạo đối tượng ObjectInputStream để đọc dữ liệu từ máy chủ
            ObjectInputStream objectInputStream = new ObjectInputStream(clientSocket.getInputStream());

            // Nhận danh sách dữ liệu từ máy chủ
            emailDataList = (List<EmailData>) objectInputStream.readObject();

            // Xử lý danh sách dữ liệu
//            for (EmailData data : emailDataList) {
//                // Thực hiện xử lý dữ liệu ở đây
//                System.out.println("Timestamp: " + data.getTimestamp());
//                System.out.println("Username: " + data.getUsername());
//                System.out.println("Subject: " + data.getSubject());
//                System.out.println("Body: " + data.getBody());
//            }
            loaddata(emailDataList);
            // Đóng kết nối và luồng đầu vào
            objectInputStream.close();
            clientSocket.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnThuguiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThuguiActionPerformed
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("Timestamp");
        tableModel.addColumn("Username");
        tableModel.addColumn("Subject");
        tableModel.addColumn("Body");
        try {
            Socket clientSocket = new Socket(SERVER_HOST, SERVER_PORT);
            DataOutputStream outputStream = new DataOutputStream(clientSocket.getOutputStream());

            outputStream.writeUTF("thudagui");
            outputStream.flush();

            // Tạo đối tượng ObjectInputStream để đọc dữ liệu từ máy chủ
            ObjectInputStream objectInputStream = new ObjectInputStream(clientSocket.getInputStream());

            // Nhận danh sách dữ liệu từ máy chủ
             emailDataList = (List<EmailData>) objectInputStream.readObject();

            // Xử lý danh sách dữ liệu
//            for (EmailData data : emailDataList) {
//                // Thực hiện xử lý dữ liệu ở đây
//                System.out.println("Timestamp: " + data.getTimestamp());
//                System.out.println("Username: " + data.getUsername());
//                System.out.println("Subject: " + data.getSubject());
//                System.out.println("Body: " + data.getBody());
//            }
            loaddata(emailDataList);
            // Đóng kết nối và luồng đầu vào
            objectInputStream.close();
            clientSocket.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnThuguiActionPerformed

    private void btnHopthudenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHopthudenActionPerformed
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("Timestamp");
        tableModel.addColumn("Username");
        tableModel.addColumn("Subject");
        tableModel.addColumn("Body");
        try {
            Socket clientSocket = new Socket(SERVER_HOST, SERVER_PORT);
            DataOutputStream outputStream = new DataOutputStream(clientSocket.getOutputStream());

            outputStream.writeUTF("hopthuden");
            outputStream.flush();

            // Tạo đối tượng ObjectInputStream để đọc dữ liệu từ máy chủ
            ObjectInputStream objectInputStream = new ObjectInputStream(clientSocket.getInputStream());

            // Nhận danh sách dữ liệu từ máy chủ
             emailDataList = (List<EmailData>) objectInputStream.readObject();

            loaddata(emailDataList);
            // Đóng kết nối và luồng đầu vào
            objectInputStream.close();
            clientSocket.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnHopthudenActionPerformed

    private void btnThuracActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThuracActionPerformed
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("Timestamp");
        tableModel.addColumn("Username");
        tableModel.addColumn("Subject");
        tableModel.addColumn("Body");
        try {
            Socket clientSocket = new Socket(SERVER_HOST, SERVER_PORT);
            DataOutputStream outputStream = new DataOutputStream(clientSocket.getOutputStream());

            outputStream.writeUTF("thurac");
            outputStream.flush();

            // Tạo đối tượng ObjectInputStream để đọc dữ liệu từ máy chủ
            ObjectInputStream objectInputStream = new ObjectInputStream(clientSocket.getInputStream());

            // Nhận danh sách dữ liệu từ máy chủ
             emailDataList = (List<EmailData>) objectInputStream.readObject();

            // Xử lý danh sách dữ liệu
//            for (EmailData data : emailDataList) {
//                // Thực hiện xử lý dữ liệu ở đây
//                System.out.println("Timestamp: " + data.getTimestamp());
//                System.out.println("Username: " + data.getUsername());
//                System.out.println("Subject: " + data.getSubject());
//                System.out.println("Body: " + data.getBody());
//            }
            loaddata(emailDataList);
            // Đóng kết nối và luồng đầu vào
            objectInputStream.close();
            clientSocket.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnThuracActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        try {
            setGD(false);

            System.out.println(emailDataList.get(jTable1.getSelectedRow()).getId());
            Socket clientSocket = new Socket(SERVER_HOST, SERVER_PORT);
            DataOutputStream outputStream = new DataOutputStream(clientSocket.getOutputStream());
            DataInputStream inputStream = new DataInputStream(clientSocket.getInputStream());

            int ID = emailDataList.get(jTable1.getSelectedRow()).getId();
            outputStream.writeUTF("laycc");
            outputStream.writeInt(ID);

            outputStream.flush();

            String listNguoiNhan = "";
            ObjectInputStream objectInputStream = new ObjectInputStream(clientSocket.getInputStream());
            List<EmailData> emailDataList2 = (List<EmailData>) objectInputStream.readObject();

            for (EmailData emailData : emailDataList2) {

                listNguoiNhan += ", " + emailData.getBody();
            }
            txtnguoidanhan.setText(listNguoiNhan.replaceFirst(", ", ""));

            String messageType = inputStream.readUTF();
            if ("attachment".equals(messageType)) {
                // Nếu là tin nhắn có tệp đính kèm, nhận và lưu tệp
                String fileName = inputStream.readUTF();

                // Lưu tệp đính kèm
                String savePath = "src\\FileDinhKemClient\\" + fileName;

                try (FileOutputStream fileOutputStream = new FileOutputStream(savePath)) {
                    byte[] buffer = new byte[4096];
                    int bytesRead;
                    while ((bytesRead = inputStream.read(buffer)) != -1) {
                        fileOutputStream.write(buffer, 0, bytesRead);
                    }
                    System.out.println("Attachment saved at: " + savePath);
                }
            }else if("no_attachment".equals(messageType)){
                System.out.println("Mail này k có file");
            }

            

            DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
            int row = jTable1.rowAtPoint(evt.getPoint());

            Object[] data = new Object[4];

            for (int i = 0; i < 4; i++) {
                data[i] = tableModel.getValueAt(row, i);
            }
            txtNguoigui.setText(data[1].toString());
            txtTieude.setText(data[2].toString());
            txtNoidung.setText(data[3].toString());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    public void setGD(boolean val) {
        if (val == true) {
            jLabel2.setText("Người Nhận");
            // btnPhanhoi.addFocusListener(fl);
            txtNoidung.setText("");
            txtTieude.setText("re: " + txtTieude.getText());

        } else {
            jLabel2.setText("Người Gửi");
        }

        jPanel2.setVisible(!val);
        btnGui.setVisible(val);
        btnPhanhoi.setVisible(!val);
    }
    private void btnPhanhoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhanhoiActionPerformed
        setGD(true);
    }//GEN-LAST:event_btnPhanhoiActionPerformed

    private void btnGuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiActionPerformed
        try {
            Socket clientSocket = new Socket(SERVER_HOST, SERVER_PORT);

            // Mở luồng gửi dữ liệu lên server
            DataOutputStream outputStream = new DataOutputStream(clientSocket.getOutputStream());

            // Gọi phương thức để gửi email
            String recipient = (txtNguoigui.getText()); // Lấy địa chỉ người nhận từ giao diện
            String subject = txtTieude.getText(); // Lấy tiêu đề từ giao diện
            String content = txtNoidung.getText(); // Lấy nội dung từ giao diện

            // Ghi các thông tin cần gửi lên server
            outputStream.writeUTF("guimail");
            outputStream.writeUTF(recipient);
            outputStream.writeUTF(subject);
            outputStream.writeUTF("NO");
            outputStream.writeUTF(content);

            outputStream.flush();

            // Nhận kết quả từ server
            DataInputStream inputStream = new DataInputStream(clientSocket.getInputStream());
            String response = inputStream.readUTF();
            JOptionPane.showMessageDialog(this, response);

            // sendMailToServer(clientSocket, outputStream, recipient, subject, content);
            // Sau khi gửi email, bạn có thể tiếp tục sử dụng kết nối và luồng cho các yêu cầu khác nếu cần.
            // Đóng kết nối khi không cần thiết nữa
            clientSocket.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnGuiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMailClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMailClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMailClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMailClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMailClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangxuat;
    private javax.swing.JButton btnGui;
    private javax.swing.JButton btnHopthuden;
    private javax.swing.JButton btnPhanhoi;
    private javax.swing.JButton btnSoanthu;
    private javax.swing.JButton btnThugui;
    private javax.swing.JButton btnThungrac;
    private javax.swing.JButton btnThurac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtNguoigui;
    private javax.swing.JTextArea txtNoidung;
    private javax.swing.JTextField txtTieude;
    private javax.swing.JTextField txtnguoidanhan;
    // End of variables declaration//GEN-END:variables
}
